spring:
  application:
    name: movieflix

  datasource:
    url: jdbc:postgresql://localhost:5432/movieflix
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true

  flyway:
    enabled: true

  springdoc:
    api-docs:
      path: /api/api-docs
    swagger-ui:
      path: /swagger/index.html

movieflix:
  security:
    secret: "palavra-secreta"
